
eureka.client.enabled=${EUREKA_CLIENT_ENABLED}
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
logging.pattern.correlation=${LOGGING_PATTERN_CORRELATION}
logging.include-application-name=${LOGGING_INCLUDE_APPLICATION_NAME}
management.tracing.sampling.probability=${MANAGEMENT_TRACING_SAMPLING_PROBABILITY}
management.zipkin.tracing.endpoint=${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT}
server.port=${SERVER_PORT}
spring.application.name=${SPRING_APPLICATION_NAME}
spring.cloud.config.enabled=${SPRING_CLOUD_CONFIG_ENABLED}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.flyway.driver-class-name=${SPRING_FLYWAY_DRIVER_CLASS_NAME}
spring.flyway.url=${SPRING_FLYWAY_URL}
spring.flyway.schemas=${SPRING_FLYWAY_SCHEMAS}
spring.flyway.user=${SPRING_FLYWAY_USER}
spring.flyway.password=${SPRING_FLYWAY_PASSWORD}

